<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OdooModelsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('odoo_models')->delete();
        
        \DB::table('odoo_models')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'commercial_category',
                'comment' => 'Catégorie commerciale',
                'dest_model' => 'template',
                'mode' => 'search',
                'field' => 'categ_id',
                'mandatory' => 1,
                'type' => NULL,
                'model' => 'product.category',
                'search_field' => 'complete_name',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'product_internal_ref',
                'comment' => 'Référence interne',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'default_code',
                'mandatory' => 0,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'product_barcode',
                'comment' => 'Code barre',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'barcode',
                'mandatory' => 0,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'product_name',
                'comment' => 'Nom du produit',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'name',
                'mandatory' => 1,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'sale_description',
                'comment' => 'Description facture',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'description_sale',
                'mandatory' => 0,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'website_description',
                'comment' => 'Description Web',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'website_description',
                'mandatory' => 0,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'brand_name',
                'comment' => 'Marque',
                'dest_model' => 'brand',
                'mode' => 'search',
                'field' => 'id',
                'mandatory' => 0,
                'type' => 'string',
                'model' => 'res.partner.category',
                'search_field' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'product_wholesale_ht',
                'comment' => 'Prix achat HT',
                'dest_model' => 'supplier',
                'mode' => 'value',
                'field' => 'price',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'product_retail_ht',
                'comment' => 'Prix public HT',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'list_price',
                'mandatory' => 1,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'product_discount_ht',
                'comment' => 'Discount price HT',
                'dest_model' => 'product discount',
                'mode' => 'value',
                'field' => 'disc_price',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'main_picture',
                'comment' => 'Photo principale',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'image_1920',
                'mandatory' => 0,
                'type' => 'image',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'alternative_pictures',
                'comment' => 'Photos additionnelles',
                'dest_model' => 'images',
                'mode' => 'value',
                'field' => 'images',
                'mandatory' => 0,
                'type' => NULL,
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'route',
                'comment' => 'Route',
                'dest_model' => 'route',
                'mode' => 'value',
                'field' => 'route_id',
                'mandatory' => 1,
                'type' => NULL,
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'type',
                'comment' => 'Odoo Type',
                'dest_model' => 'template',
                'mode' => 'value',
                'field' => 'type',
                'mandatory' => 1,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'tax',
                'comment' => 'Taxes',
                'dest_model' => 'template',
                'mode' => 'search_multiple',
                'field' => 'taxes_id',
                'mandatory' => 1,
                'type' => NULL,
                'model' => 'account.tax',
                'search_field' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'variant_internal_ref',
                'comment' => 'Référence interne variante',
                'dest_model' => 'variant',
                'mode' => 'value',
                'field' => 'default_code',
                'mandatory' => 0,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'variant_barcode',
                'comment' => 'Code barre variante',
                'dest_model' => 'variant',
                'mode' => 'value',
                'field' => 'barcode',
                'mandatory' => 0,
                'type' => 'string',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'variant_picture',
                'comment' => 'Photo variante',
                'dest_model' => 'variant',
                'mode' => 'value',
                'field' => 'image_1920',
                'mandatory' => 0,
                'type' => 'image',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'variant_wholesale_ht',
                'comment' => 'Prix Achat variante',
                'dest_model' => 'variant supplier',
                'mode' => 'value',
                'field' => 'price',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'variant_cost_ht',
                'comment' => 'Cout variante HT',
                'dest_model' => 'variant',
                'mode' => 'value',
                'field' => 'standard_price',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'variant_retail_ht',
                'comment' => 'Prix public variante HT',
                'dest_model' => 'variant price',
                'mode' => 'value',
                'field' => 'price',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'name' => 'variant_discount_ht',
                'comment' => 'Discount price variante HT',
                'dest_model' => 'variant price',
                'mode' => 'value',
                'field' => 'disc_price',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'name' => 'variant_weight',
                'comment' => 'Poids',
                'dest_model' => 'variant',
                'mode' => 'value',
                'field' => 'weight',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'name' => 'variant_volume',
                'comment' => 'Volume',
                'dest_model' => 'variant',
                'mode' => 'value',
                'field' => 'volume',
                'mandatory' => 0,
                'type' => 'float',
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'name' => 'inventory',
                'comment' => 'Stock',
                'dest_model' => 'inventory',
                'mode' => 'value',
                'field' => 'inventory_quantity',
                'mandatory' => 0,
                'type' => NULL,
                'model' => NULL,
                'search_field' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'name' => 'owner',
                'comment' => 'Propriétaire',
                'dest_model' => 'inventory',
                'mode' => 'search',
                'field' => 'partner_id',
                'mandatory' => 0,
                'type' => NULL,
                'model' => 'res.partner',
                'search_field' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'name' => 'attribute',
                'comment' => 'attribute',
                'dest_model' => 'variant',
                'mode' => 'search',
                'field' => 'attribute_id',
                'mandatory' => 0,
                'type' => 'string',
                'model' => 'product.attribute.value',
                'search_field' => 'name',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}